---
spring:
  application:
    name: app
  profiles:
    default: dev
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

app:
  task-statuses: >
    draft,
    to_review,
    to_be_fixed,
    to_publish,
    published
  labels: >
    feature,
    bug

server:
  address: 0.0.0.0