---
spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:dev;DB_CLOSE_DELAY=-1;LOCK_MODE=0
  output:
    ansi:
      enabled: always

app:
  user:
    email: hexlet@example.com
    password: qwerty

logging:
  level:
    root: WARN
    org:
      springframework:
        web: DEBUG
        security: DEBUG