---
sentry:
  dsn: ${SENTRY_AUTH_TOKEN:https://examplePublicKey@o0.ingest.sentry.io/0}
  tracesSampleRate: 1.0

app:
  user:
    email: ${USER_EMAIL:hexlet@example.com}
    password: ${USER_PASSWORD:qwerty}

logging:
  level:
    root: INFO