---
spring:
  profiles:
    active: stage
  datasource:
    url: ${ JDBC_DATABASE_URL }
    driver-class-name: ${ JDBC_DRIVER }

app:
  user:
    email: ${ USER_EMAIL }
    password: ${ USER_PASSWORD }

logging:
  level:
    root: INFO