---
spring:
  profiles:
    default: dev
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger
    enabled: true

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

app:
  task-statuses: >
    draft,
    to_review,
    to_be_fixed,
    to_publish,
    published,
    feature,
    bug

server:
  address: 0.0.0.0