---
app:
  user:
    email: ${ USER_EMAIL }
    password: ${ USER_PASSWORD }

spring:
  profiles:
    active: stage
  datasource:
    url: ${ JDBC_DATABASE_URL }
    driver-class-name: org.postgresql.Driver

logging:
  level:
    root: WARN